### ISSUE TITLE
Feature request: Support XDG Specification

### ISSUE THREAD

**Issue by Jackymancs4** [smallwat3r/sketch#2]
Hello @smallwat3r 
Saw this little thing on reddit, and I like the concept. Very similar to my own workflow.

But I tend to be quite conscious about the 'do not pollute userspace' rule, so I have two suggestions:

Look for `.sketchconfig` in

1. `.`
2. `$XDG_CONFIG_HOME` if defined
3. `$HOME/.config` (default for XDG_CONFIG_HOME)
4. `$HOME` (actual behavior)

in this order.

And set `$TEMP_SKETCH` as `$XDG_DATA_HOME` if defined or default it to `$HOME/.local/share` (default for XDG_DATA_HOME)

Since configuration is indeed important, maybe you can add `sketch_dir` to `.sketchconfig`, source it before https://github.com/smallwat3r/sketch/blob/0885b85aa12f145ba187a36f225584f4df152748/src/sketch#L12-L19
and set $TEMP_SKETCH as

1. `sketch_dir` if defined
2. `XDG_DATA_HOME` if defined
3. `$HOME/.local/share`

in this order.

I took the defaults value here:
https://wiki.archlinux.org/index.php/XDG_Base_Directory#User_directories

Thanks!

**Comment by smallwat3r** [comment]
Hi @Jackymancs4 

Thanks, really appreciate your feedback, these are great ideas.

I made some changes and you can now allocate a default folder from `.sketchconfig`. I've also added default support for XDG if exists.

Thanks !
