### ISSUE TITLE
Feauture request: version flag

### ISSUE THREAD

**Issue by Jackymancs4** [smallwat3r/sketch#3]
Hey @smallwat3r 
Here another idea:
I see you already made a release tag, so if you plan to version this project (and after #2 I think it's ready for a 1.1 release), adding a `-v | --version` command flag could be very useful to track updates.

**Comment by smallwat3r** [comment]
Hey @Jackymancs4 
That is actually a really good point, as you said - much easier to track updates.
I added a new parameter `-v | --version` to output release number.
Also did a new 1.1 release.
Thanks !
